EXP_NAME: MyModel
TASK: classify
METHOD: supervised
API_KEY: 'c1d91b9d8d01d41c563d2ed88216016fef6fdf5a' # tài khoản wandb
SEED: 42

DATASET:
    datadir: 'datasets/classifydata'
    target: 'garbage'
    mode: True
    resize:
      - 256 # height 224
      - 256 # width 224
    aug:
        random_crop:
            prob: 0.5
            scale: [0.87, 1.15] # range of size of the origin size cropped
            ratio: [0.7, 1.3] # range of aspect ratio of the origin aspect ratio cropped
            option: True
        horizontal_flip:
            prob: 0.5
            option: True
        vertical_flip:
            prob: 0.5
            option: True
        color_distortion:
            prob: 0.5
            brightness: 0.2
            contrast: 0.2
            saturation: 0.2
            hue: 0.1
            option: True
        rotation:
            prob: 0.5
            degrees: [-180, 180]
            value_fill: 0
            option: True
        translation:
            prob: 0.5
            range: [0.2, 0.2]
            value_fill: 0
            option: True

DATALOADER:
    batch_size: 8 # 32
    num_workers: 2

MODEL:
    backbone: 'resnet50'
    pretrained: True

TRAIN:
    epochs: 100
    use_gpu: True
    use_wandb: True
    visualize_aug: True
    num_sample: 5
    export_to_onnx: True
    num_train : 0.9
    ckp_metric: 'bcr' # 'bcr' 'acc'
    loss_name: 'bcr' # 'bcr' 'ce'

OPTIMIZER:
    adam:
        option: False  
        lr: 0.001     
        weight_decay: 0.
    adamw:
        option: True  
        lr: 0.001     
        weight_decay: 0.0001
    sgd:
        option: False  
        lr: 0.001      
        momentum: 0.9
        weight_decay: 0.0001
    sophiag:
        option: False
        lr: 0.0001
        weight_decay: 0.1  
        rho: 0.03

SCHEDULER:
    use_scheduler: True
    cosine_annealing_warmup_restarts:
        min_lr: 0.0001
        warmup_ratio: 0.1
        option: False
    step_lr:
        option: False
        gamma: 0.1
    cosine_annealing_lr:
        option: True
    lambda_lr:
        option: True
        scheduler_name: 'linear'

LOG:
    log_interval: 1
    eval_interval: 1

RESULT:
    savedir: 'saved_model'
    saveall: 'save_all_result'
    save_test_img: 'save_test_image'
    saveallonnx: 'save_all_result_onnx'
    save_test_img_onnx: 'save_test_img_onnx'

RESUME:
    option: True
    opset_version: 13
    bestmodel: 'best_model.pth'
    onnxmodel: 'best_model.onnx'