EXP_NAME: CFlow
TASK: anomaly
METHOD: unsupervised
API_KEY: 'c1d91b9d8d01d41c563d2ed88216016fef6fdf5a' # tài khoản wandb
SEED: 42

DATASET:
    datadir: 'datasets/anomaly/mvtec'
    target: 'bottle'
    mode: True
    resize:
      - 256 # height
      - 256 # width

DATALOADER:
    batch_size: 2
    num_workers: 2

MODEL:
    backbone: 'wide_resnet50_2'
    pre_trained: true
    layers:
        - layer2
        - layer3
        - layer4
    decoder: 'freia-cflow'
    condition_vector: 128
    coupling_blocks: 8
    clamp_alpha: 1.9
    fiber_batch_size: 64
    permute_soft: false

TRAIN:
    num_training_steps: 3000
    use_gpu: True
    use_wandb: True
    top_k: 100
    compute_threshold: True
    beta: 1.0
    visualize_aug: True
    num_sample: 5
    export_to_onnx: True

TEST:
    threshold_pixel: 0.5
    threshold_image: 0.5

OPTIMIZER:
    adam:
        option: False  
        lr: 0.001     
        weight_decay: 0.
    adamw:
        option: True  
        lr: 0.0001     
        weight_decay: 0.0001
    sgd:
        option: False  
        lr: 0.001      
        momentum: 0.9
        weight_decay: 0.0001
    sophiag:
        option: False
        lr: 0.0001
        weight_decay: 0.1  
        rho: 0.03

SCHEDULER:
    use_scheduler: True
    cosine_annealing_warmup_restarts:
        min_lr: 0.00001
        warmup_ratio: 0.1
        option: True
    step_lr:
        option: False
        gamma: 0.1
    cosine_annealing_lr:
        option: False
    lambda_lr:
        option: False
        scheduler_name: 'linear'

LOG:
    log_interval: 1
    eval_interval: 100

RESULT:
    savedir: 'saved_model'
    saveall: 'save_all_result'
    save_test_img: 'save_test_image'
    saveallonnx: 'save_all_result_onnx'
    save_test_img_onnx: 'save_test_img_onnx'

RESUME:
    option: True
    opset_version: 13
    bestmodel: 'best_model.pth'
    onnxmodel: 'best_model.onnx'