EXP_NAME: EAST
TASK: textdetection
METHOD: supervised
API_KEY: 'c1d91b9d8d01d41c563d2ed88216016fef6fdf5a' # tài khoản wandb
SEED: 42

DATASET:
    datadir: 'datasets/text_detection_data'
    target: 'icdar13'
    test_folder: 'icdar13'
    mode: True
    resize: 
        - 512 # height
        - 512 # width
    scale: 0.25

DATALOADER:
    batch_size: 1
    num_workers: 2

MODEL:
    backbone: 'resnet50'
    pretrained: True
    inner_channels: 256

TRAIN:
    fine_tuning: True
    weights_pretrained: 'saved_model/textdetection/supervised/synth/EAST-resnet50/best_model.pth'
    epochs: 10
    visualize_aug: True
    num_sample: 5
    use_gpu: True
    use_wandb: True
    export_to_onnx: True

TEST:
    score_thresh: 0.8
    nms_thresh: 0.2
    cover_thresh: 0.1

OPTIMIZER:
    adam:
        option: True  
        lr: 0.001     
        weight_decay: 0.
    adamw:
        option: False  
        lr: 0.001     
        weight_decay: 0.0001
    sgd:
        option: False  
        lr: 0.001      
        momentum: 0.9
        weight_decay: 0.0001
    sophiag:
        option: False
        lr: 0.001
        weight_decay: 0.1  
        rho: 0.03

SCHEDULER:
    use_scheduler: True
    cosine_annealing_warmup_restarts:
        min_lr: 0.0001
        warmup_ratio: 0.1
        option: False
    step_lr:
        option: False
        gamma: 0.1
    cosine_annealing_lr:
        option: False
    lambda_lr:
        option: True
        scheduler_name: 'linear'

LOG:
    log_interval: 1
    eval_interval: 1

RESULT:
    savedir: 'saved_model'
    saveall: 'save_all_result'
    save_test_img: 'save_test_image'
    saveallonnx: 'save_all_result_onnx'
    save_test_img_onnx: 'save_test_img_onnx'
    vis_test_dir: 'vis_test_icdar13_dir'

RESUME:
    option: True
    opset_version: 13
    bestmodel: 'best_model.pth'
    onnxmodel: 'best_model.onnx'