EXP_NAME: DexiNed
TASK: edgedetection
METHOD: supervised
API_KEY: 'c1d91b9d8d01d41c563d2ed88216016fef6fdf5a' # tài khoản wandb
SEED: 42

DATASET:
    datadir: 'datasets/edge_detection_data'
    target: 'brind'
    mode: True
    resize:
      - 512 # height
      - 512 # width
    threshold: 0.3
    
DATALOADER:
    batch_size: 2
    num_workers: 2

MODEL:
    backbone: 'cnn'

TRAIN:
    epochs: 20
    # loss_weights: [0.7, 0.7, 1.1, 0.7, 1.3]
    loss_weights: [[0.05, 2.], [0.05, 2.], [0.05, 2.], [0.1, 1.], [0.1, 1.], [0.1, 1.], [0.01, 4.]]
    use_gpu: True
    use_wandb: True
    visualize_aug: True
    num_sample: 5
    export_to_onnx: True
    num_train : 0.9

OPTIMIZER:
    adam:
        option: True  
        lr: 0.00005    
        weight_decay: 0.000005
    adamw:
        option: False  
        lr: 0.001     
        weight_decay: 0.0001
    sgd:
        option: False  
        lr: 0.001      
        momentum: 0.9
        weight_decay: 0.0001
    sophiag:
        option: False
        lr: 0.001
        weight_decay: 0.1  
        rho: 0.03

SCHEDULER:
    use_scheduler: True
    cosine_annealing_warmup_restarts:
        min_lr: 0.00001
        warmup_ratio: 0.1
        option: False
    step_lr:
        option: False
        gamma: 0.1
    cosine_annealing_lr:
        option: False
    lambda_lr:
        option: True
        scheduler_name: 'linear'

LOG:
    log_interval: 1

RESULT:
    savedir: 'saved_model'
    saveall: 'save_all_result'
    save_test_img: 'save_test_image'
    saveallonnx: 'save_all_result_onnx'
    save_test_img_onnx: 'save_test_img_onnx'
    vis_train_dir: 'vis_train_bsds_dir'
    vis_test_dir: 'vis_test_bsds_dir'

RESUME:
    option: True
    opset_version: 13
    bestmodel: 'best_model.pth'
    onnxmodel: 'best_model.onnx'