EXP_NAME: CRNN
TASK: textrecognition
METHOD: supervised
API_KEY: 'c1d91b9d8d01d41c563d2ed88216016fef6fdf5a' # tài khoản wandb
SEED: 42

DATASET:
    datadir: 'datasets/text_recognition_data'
    target: 'icdar15'
    synth_folder: 'synth90k'
    test_folder: 'icdar15'
    mode: False
    chars: '0123456789abcdefghijklmnopqrstuvwxyz'
    resize: 
        - 32 # height
        - 100 # width
  
DATALOADER:
    batch_size: 128
    num_workers: 2

MODEL:
    backbone: 'cnn'
    img_channel: 1
    map_to_seq_hidden: 64
    rnn_hidden: 256
    leaky_relu: False

TRAIN:
    num_training_steps: 100000
    fine_tuning: True
    weights_pretrained: 'saved_model/ocr/text_recognition/synth90k/CRNN-cnn/best_model.pth'
    visualize_augmentations: True
    samples: 5
    use_gpu: True
    use_wandb: True
    decode_method: 'beam_search'
    beam_size: 10
    export_to_onnx: True

OPTIMIZER:
    adam:
        option: True  
        lr: 0.001     
        weight_decay: 0.001
    adamw:
        option: False  
        lr: 0.001     
        weight_decay: 0.0001
    sgd:
        option: False  
        lr: 0.001      
        momentum: 0.9
        weight_decay: 0.0001
    sophiag:
        option: False
        lr: 0.0001
        weight_decay: 0.1  
        rho: 0.03

SCHEDULER:
    use_scheduler: True
    cosine_annealing_warmup_restarts:
        min_lr: 0.0001
        warmup_ratio: 0.1
        option: True
    step_lr:
        option: False
        gamma: 0.1
    cosine_annealing_lr:
        option: False
    lambda_lr:
        option: True
        scheduler_name: 'linear'

LOG:
    log_interval: 1
    eval_interval: 1000

RESULT:
    savedir: 'saved_model'
    saveall: 'save_all_result'
    save_test_img: 'save_test_image'
    saveallonnx: 'save_all_result_onnx'
    save_test_img_onnx: 'save_test_img_onnx'

RESUME:
    option: True
    opset_version: 13
    bestmodel: 'best_model.pth'
    onnxmodel: 'best_model.onnx'