EXP_NAME: RTCDet
TASK: objectdetection
METHOD: supervised
API_KEY: 'c1d91b9d8d01d41c563d2ed88216016fef6fdf5a' # tài khoản wandb
SEED: 42

DATASET:
    datadir: 'datasets/object_detection_data'
    target: 'fruits'
    resize: 
        - 640 # height
        - 640 # width
    mode: True
    keep_difficult: False
    class_names:
    - kiwifruit
    - orange
    - lemon
    - cherry
    trans_config:
        min_visibility: 0.4
        horizontal_flip:
            prob: 0.5
            option: True
        blur:
            prob: 0.1
            option: True
        clahe:
            prob: 0.1
            option: True
        posterize:
            prob: 0.1
            option: True
        togray:
            prob: 0.1
            option: True
        channelshuffle:
            prob: 0.05
            option: True
        color_distortion:
            prob: 0.4
            brightness: 0.6
            contrast: 0.6
            saturation: 0.6
            hue: 0.6
            option: True
        translation:
            prob: 1.0
            rotate_limit: 20
            shear: 15
            p: 0.5
            option: True

DATALOADER:
    batch_size: 4
    num_workers: 2

MODEL:
    model_type: 'rtcdet_n'
    rtcdet_p:
        # backbone
        backbone: elannet_v2
        pretrained: True
        bk_act: silu
        bk_norm: BN
        bk_depthwise: True
        width: 0.25
        depth: 0.34
        stride: [8, 16, 32]  # P3, P4, P5
        max_stride: 32
        reg_max: 16
        # neck: SPP
        neck: sppf
        neck_expand_ratio: 0.5
        pooling_size: 5
        neck_act: silu
        neck_norm: BN
        neck_depthwise: True
        # neck: PaFPN
        fpn: rtcdet_pafpn
        fpn_reduce_layer: conv
        fpn_downsample_layer: conv
        fpn_core_block: elan_block
        fpn_branch_depth: 3
        fpn_expand_ratio: 0.5
        fpn_act: silu
        fpn_norm: BN
        fpn_depthwise: True
        # head
        head: decoupled_head
        head_act: silu
        head_norm: BN
        num_cls_head: 2
        num_reg_head: 2
        head_depthwise: True
        
    rtcdet_n:
        # backbone
        backbone: elannet_v2
        pretrained: True
        bk_act: silu
        bk_norm: BN
        bk_depthwise: False
        width: 0.25
        depth: 0.34
        stride: [8, 16, 32]  # P3, P4, P5
        max_stride: 32
        reg_max: 16
        # neck: SPP
        neck: sppf
        neck_expand_ratio: 0.5
        pooling_size: 5
        neck_act: silu
        neck_norm: BN
        neck_depthwise: False
        # neck: PaFPN
        fpn: rtcdet_pafpn
        fpn_reduce_layer: conv
        fpn_downsample_layer: conv
        fpn_core_block: elan_block
        fpn_branch_depth: 3
        fpn_expand_ratio: 0.5
        fpn_act: silu
        fpn_norm: BN
        fpn_depthwise: False
        # head
        head: decoupled_head
        head_act: silu
        head_norm: BN
        num_cls_head: 2
        num_reg_head: 2
        head_depthwise: False

    rtcdet_t:
        # backbone
        backbone: elannet_v2
        pretrained: True
        bk_act: silu
        bk_norm: BN
        bk_depthwise: False
        width: 0.375
        depth: 0.34
        stride: [8, 16, 32]  # P3, P4, P5
        max_stride: 32
        reg_max: 16
        # neck: SPP
        neck: sppf
        neck_expand_ratio: 0.5
        pooling_size: 5
        neck_act: silu
        neck_norm: BN
        neck_depthwise: False
        # neck: PaFPN
        fpn: rtcdet_pafpn
        fpn_reduce_layer: conv
        fpn_downsample_layer: conv
        fpn_core_block: elan_block
        fpn_branch_depth: 3
        fpn_expand_ratio: 0.5
        fpn_act: silu
        fpn_norm: BN
        fpn_depthwise: False
        # head
        head: decoupled_head
        head_act: silu
        head_norm: BN
        num_cls_head: 2
        num_reg_head: 2
        head_depthwise: False

    rtcdet_s:
        # backbone
        backbone: elannet_v2
        pretrained: True
        bk_act: silu
        bk_norm: BN
        bk_depthwise: False
        width: 0.5
        depth: 0.34
        stride: [8, 16, 32]  # P3, P4, P5
        max_stride: 32
        reg_max: 16
        # neck: SPP
        neck: sppf
        neck_expand_ratio: 0.5
        pooling_size: 5
        neck_act: silu
        neck_norm: BN
        neck_depthwise: False
        # neck: PaFPN
        fpn: rtcdet_pafpn
        fpn_reduce_layer: conv
        fpn_downsample_layer: conv
        fpn_core_block: elan_block
        fpn_branch_depth: 3
        fpn_expand_ratio: 0.5
        fpn_act: silu
        fpn_norm: BN
        fpn_depthwise: False
        # head
        head: decoupled_head
        head_act: silu
        head_norm: BN
        num_cls_head: 2
        num_reg_head: 2
        head_depthwise: False

    rtcdet_m:
        # backbone
        backbone: elannet_v2
        pretrained: False
        bk_act: silu
        bk_norm: BN
        bk_depthwise: False
        width: 0.75
        depth: 0.67
        stride: [8, 16, 32]  # P3, P4, P5
        max_stride: 32
        reg_max: 16
        # neck: SPP
        neck: sppf
        neck_expand_ratio: 0.5
        pooling_size: 5
        neck_act: silu
        neck_norm: BN
        neck_depthwise: False
        # neck: PaFPN
        fpn: rtcdet_pafpn
        fpn_reduce_layer: conv
        fpn_downsample_layer: conv
        fpn_core_block: elan_block
        fpn_branch_depth: 3
        fpn_expand_ratio: 0.5
        fpn_act: silu
        fpn_norm: BN
        fpn_depthwise: False
        # head
        head: decoupled_head
        head_act: silu
        head_norm: BN
        num_cls_head: 2
        num_reg_head: 2
        head_depthwise: False

    rtcdet_l:
        # backbone
        backbone: elannet_v2
        pretrained: False
        bk_act: silu
        bk_norm: BN
        bk_depthwise: False
        width: 1.0
        depth: 1.0
        stride: [8, 16, 32]  # P3, P4, P5
        max_stride: 32
        reg_max: 16
        # neck: SPP
        neck: sppf
        neck_expand_ratio: 0.5
        pooling_size: 5
        neck_act: silu
        neck_norm: BN
        neck_depthwise: False
        # neck: PaFPN
        fpn: rtcdet_pafpn
        fpn_reduce_layer: conv
        fpn_downsample_layer: conv
        fpn_core_block: elan_block
        fpn_branch_depth: 3
        fpn_expand_ratio: 0.5
        fpn_act: silu
        fpn_norm: BN
        fpn_depthwise: False
        # head
        head: decoupled_head
        head_act: silu
        head_norm: BN
        num_cls_head: 2
        num_reg_head: 2
        head_depthwise: False

TRAIN:
    epochs: 100
    no_aug_epoch: 20
    center_sampling_radius: 2.5
    topk_candidate: 10
    loss_cls_weight: 1.0
    loss_dfl_weight: 1.0
    loss_iou_weight: 5.0
    ema_update: False
    loss_box_aux: True
    use_gpu: True
    use_wandb: True
    visualize_aug: True
    num_sample: 5
    export_to_onnx: True
    # base weigth
    base_weight: 'task/objectdetection/supervised/base_weights'
    # decode
    conf_thresh: 0.2
    nms_thresh: 0.45
    topk: 100
    no_decode: False

TEST:
    # decode
    conf_thresh: 0.2
    nms_thresh: 0.45
    topk: 100
    no_decode: True
    is_anchor: False
    vis_thresh: 0.3

VIDEO:
    track_thresh: 0.5
    track_buffer: 30
    frame_rate: 30
    match_thresh: 0.8
    mot20: False
    aspect_ratio_thresh: 1.6
    min_box_area: 10
    is_visual_class: False

OPTIMIZER:
    adam:
        option: True  
        lr: 0.0001     
        weight_decay: 0.
    adamw:
        option: False  
        lr: 0.001    
        weight_decay: 0.0001
    sgd:
        option: False  
        lr: 0.001
        momentum: 0.9
        weight_decay: 0.0005
    sophiag:
        option: False
        lr: 0.0006
        weight_decay: 0.2
        rho: 0.05

SCHEDULER:
    use_scheduler: True
    cosine_annealing_warmup_restarts:
        min_lr: 0.0001
        warmup_ratio: 0.1
        option: False
    step_lr:
        option: False
        gamma: 0.1
    cosine_annealing_lr:
        option: False
    lambda_lr:
        option: True
        scheduler_name: 'linear'

LOG:
    log_interval: 1
    eval_interval: 1

RESULT:
    savedir: 'saved_model'
    saveall: 'save_all_result'
    save_test_img: 'save_test_image'
    saveallonnx: 'save_all_result_onnx'
    save_test_img_onnx: 'save_test_img_onnx'
    vis_test_dir: 'vis_test_dir'
    save_track_camera: 'save_track_camera'
    save_track_camera_onnx: 'save_track_camera_onnx'
    save_track_video: 'save_track_video'
    save_track_video_onnx: 'save_track_video_onnx'

RESUME:
    option: True
    opset_version: 13
    bestmodel: 'best_model.pth'
    onnxmodel: 'best_model.onnx'