EXP_NAME: RTTDet
TASK: textdetection
METHOD: weaklysupervised
API_KEY: 'c1d91b9d8d01d41c563d2ed88216016fef6fdf5a' # tài khoản wandb
SEED: 42

DATASET:
    datadir: 'datasets/text_detection_data'
    target: 'icdar15'
    synth_folder: 'synth'
    test_folder: 'icdar15'
    mode: True
    pseudo_vis_opt: True
    do_not_care_label: 
        - '###'
        -  ''
    resize: 
        - 512 # height
        - 512 # width
    gauss_init_size: 200
    gauss_sigma: 40
    enlarge_region: 
        - 0.5 # x axis
        - 0.5 # y axis
    enlarge_affinity: 
        - 0.5 # x axis
        - 0.5 # y axis
    syn_aug:
        random_scale:
            range: [1.0, 1.5, 2.0]
            prob: 0.6
            option: True
        random_rotate:
            max_angle: 20
            prob: 0.5
            option: True
        random_horizontal_flip:
            prob: 0.5
            option: True
        random_colorjitter:
            brightness: 0.2
            contrast: 0.2
            saturation: 0.2
            hue: 0.2
            prob: 0.5
            option: True
    icdar_aug:
        random_scale:
            range: [1.0, 1.5, 2.0]
            prob: 0.6
            option: False
        random_rotate:
            max_angle: 20
            prob: 0.5
            option: True
        random_horizontal_flip:
            prob: 0.5
            option: True
        random_colorjitter:
            brightness: 0.2
            contrast: 0.2
            saturation: 0.2
            hue: 0.2
            prob: 0.5
            option: True

DATALOADER:
    batch_size: 1
    num_workers: 2

MODEL:
    model_size: 'rttdet_s'
    rttdet_n:
        # backbone                      
        backbone: 'cspdarknet'
        pretrained: True
        bk_act: 'silu'
        bk_norm: 'BN'
        bk_dpw: False
        width: 0.25
        depth: 0.34
        # head
        head_act: 'silu'
        head_norm: 'BN'
        head_depthwise: False
        
    rttdet_s:
        # backbone                      
        backbone: 'cspdarknet'
        pretrained: True
        bk_act: 'silu'
        bk_norm: 'BN'
        bk_dpw: False
        width: 0.5
        depth: 0.34
        # head
        head_act: 'silu'
        head_norm: 'BN'
        head_depthwise: False

    rttdet_m:
        # backbone                      
        backbone: 'cspdarknet'
        pretrained: False
        bk_act: 'silu'
        bk_norm: 'BN'
        bk_dpw: False
        width: 0.75
        depth: 0.67
        # head
        head_act: 'silu'
        head_norm: 'BN'
        head_depthwise: False

    rttdet_l:
        # backbone                      
        backbone: 'cspdarknet'
        pretrained: False
        bk_act: 'silu'
        bk_norm: 'BN'
        bk_dpw: False
        width: 1.0
        depth: 1.0
        # head
        head_act: 'silu'
        head_norm: 'BN'
        head_depthwise: False
    
    rttdet_x:
        # backbone                      
        backbone: 'cspdarknet'
        pretrained: False
        bk_act: 'silu'
        bk_norm: 'BN'
        bk_dpw: False
        width: 1.25
        depth: 1.34
        # head
        head_act: 'silu'
        head_norm: 'BN'
        head_depthwise: False

TRAIN:
    fine_tuning: True
    weights_pretrained: 'saved_model/textdetection/weaklysupervised/synth/CRAFT-resnet50/best_model.pth'
    num_training_steps: 200000
    visualize_augmentations: True
    samples: 20
    neg_rto: 0.3
    n_min_neg: 5000
    use_gpu: True
    use_wandb: True
    export_to_onnx: True

TEST:
    text_threshold: 0.75 # 0.85
    low_text: 0.5
    link_threshold: 0.2

OPTIMIZER:
    adam:
        option: True  
        lr: 0.001     
        weight_decay: 0.
    adamw:
        option: False  
        lr: 0.001     
        weight_decay: 0.0001
    sgd:
        option: False  
        lr: 0.001      
        momentum: 0.9
        weight_decay: 0.0001
    sophiag:
        option: False
        lr: 0.0001
        weight_decay: 0.1  
        rho: 0.03

SCHEDULER:
    use_scheduler: True
    cosine_annealing_warmup_restarts:
        min_lr: 0.0001
        warmup_ratio: 0.1
        option: False
    step_lr:
        option: True
        gamma: 0.1
    cosine_annealing_lr:
        option: False
    lambda_lr:
        option: True
        scheduler_name: 'linear'

LOG:
    log_interval: 1
    eval_interval: 1000

RESULT:
    savedir: 'saved_model'
    saveall: 'save_all_result'
    save_test_img: 'save_test_image'
    saveallonnx: 'save_all_result_onnx'
    save_test_img_onnx: 'save_test_img_onnx'
    vis_train_dir: 'vis_train_icdar13_dir'
    vis_test_dir: 'vis_test_icdar13_dir'

RESUME:
    option: True
    opset_version: 13
    bestmodel: 'best_model.pth'
    onnxmodel: 'best_model.onnx'